version: '3'
services:
    backend:
        build: .
        image: comp90024-backend:latest
        ports:
            # port number on server that others can access: port number in container
            - "80:5000"
        environment:
            # port number that you want the flask to listen to
            http_proxy: http://wwwproxy.unimelb.edu.au:8000/
            https_proxy: http://wwwproxy.unimelb.edu.au:8000/
            HTTP_PROXY: http://wwwproxy.unimelb.edu.au:8000/
            HTTPS_PROXY: http://wwwproxy.unimelb.edu.au:8000/
            no_proxy: localhost,127.0.0.1,localaddress,172.16.0.0/12,.melbourne.rc.nectar.org.au,.storage.u nimelb.edu.au,.cloud.unimelb.edu.au
        deploy:
            restart_policy: "unless-stopped"
    