FROM python:3

COPY harvester/config.py /harvester/
COPY harvester/stream_tweet.py /harvester/
COPY requirements.txt /tmp
RUN pip install -r /tmp/requirements.txt

WORKDIR /harvester
EXPOSE 80
CMD ["python", "stream_tweet.py"]