---
- name: Copy GitHub private key to server
  copy:
    src: "config/github.pem"
    dest: /home/ubuntu/.ssh/github
    owner: ubuntu
    group: ubuntu
    mode: 0600

- name: git pull repository
  shell: git pull
  args:
    chdir: '{{ git_repo }}'

- name: Remove github key
  file:
    path: /home/ubuntu/.ssh/github
    state: absent

# - name: Log into DockerHub
#   docker_login:
#     registry: https://index.docker.io/v1/
#     username: "{{ username }}"
#     password: "{{ password }}"
#   delegate_to: localhost

# - name: docker build & push to registry 
#   shell: docker build --no-cache -t {{ image_name }} . && docker push {{ image_name }}
#   delegate_to: localhost
#   args:
#     chdir: "../frontend/"

# - name: Log into DockerHub
#   become: yes 
#   docker_login:
#     registry: https://index.docker.io/v1/
#     username: "{{ username }}"
#     password: "{{ password }}"

- name: Docker run when ports defind and volumes not defined
  become: yes 
  docker_container:
    name: "frontend"
    image: "radhidj/frontend:latest"
    command: ""
    restart_policy: "unless-stopped"
    ports:
      - "80:3000"
    env:
      http_proxy: http://wwwproxy.unimelb.edu.au:8000/
      https_proxy: http://wwwproxy.unimelb.edu.au:8000/
      HTTP_PROXY: http://wwwproxy.unimelb.edu.au:8000/
      HTTPS_PROXY: http://wwwproxy.unimelb.edu.au:8000/
      no_proxy: localhost,127.0.0.1,localaddress,172.16.0.0/12,.melbourne.rc.nectar.org.au,.storage.u nimelb.edu.au,.cloud.unimelb.edu.au
  with_sequence: count=1
  loop_control:
    loop_var: seq
  tags:
    - docker-run