---
- name: Copy GitHub private key to server
  copy:
    src: "config/github.pem"
    dest: /home/ubuntu/.ssh/github
    owner: ubuntu
    group: ubuntu
    mode: 0600

- name: git pull repository
  shell: git pull
  args:
    chdir: '{{ git_repo }}'

- name: Remove github key
  file:
    path: /home/ubuntu/.ssh/github
    state: absent

- name: Create package file
  become: 
    yes
  template:
    src: package.j2
    dest: '{{remote_working_directory}}/ccc_assg2/frontend/package.json'

- name: Shut down previous server
  become:
    yes
  shell: docker-compose down --rmi local
  args:
    chdir: /home/ubuntu/COMP90024/ccc_assg2/frontend

- name: Start server
  shell: docker-compose up -d --build
  args:
    chdir: /home/ubuntu/COMP90024/ccc_assg2/frontend