---
- name: Copy GitHub private key to server
  copy:
    src: "config/github.pem"
    dest: /home/ubuntu/.ssh/github
    owner: ubuntu
    group: ubuntu
    mode: 0600

- name: git pull repository
  shell: git pull
  args:
    chdir: '{{ git_repo }}'

- name: Remove github key
  file:
    path: /home/ubuntu/.ssh/github
    state: absent

- name: Create db connection file
  become: 
    yes
  template:
    src: connectDB.j2
    dest: '{{remote_working_directory}}/ccc_assg2/backend/connectDB.py'

- name: Shut down previous server
  become:
    yes
  shell: docker-compose down --rmi local
  args:
    chdir: /home/ubuntu/COMP90024/ccc_assg2/backend

- name: Start server
  shell: docker-compose up -d --build
  args:
    chdir: /home/ubuntu/COMP90024/ccc_assg2/backend

# - name: Log into DockerHub
#   docker_login:
#     registry: https://index.docker.io/v1/
#     username: "{{ username }}"
#     password: "{{ password }}"
#   delegate_to: localhost

# - name: docker build & push to registry 
#   shell: docker build --no-cache -t {{ image_name }} . && docker push {{ image_name }}
#   delegate_to: localhost
#   args:
#     chdir: "../backend/"

# - name: Log into DockerHub
#   become: yes 
#   docker_login:
#     registry: https://index.docker.io/v1/
#     username: "{{ username }}"
#     password: "{{ password }}"

# - name: Docker run when ports defind and volumes not defined
#   become: yes 
#   docker_container:
#     name: "backend"
#     image: "radhidj/backend:latest"
#     command: ""
#     restart_policy: "unless-stopped"
#     ports:
#       - "80:5000"
#   with_sequence: count=1
#   loop_control:
#     loop_var: seq
#   tags:
#     - docker-run