---
- name: Copy GitHub private key to server
  copy:
    src: "config/github.pem"
    dest: /home/ubuntu/.ssh/github
    owner: ubuntu
    group: ubuntu
    mode: 0600

- name: git pull repository
  shell: git pull
  args:
    chdir: '{{ git_repo }}'

- name: Remove github key
  file:
    path: /home/ubuntu/.ssh/github
    state: absent

- name: Create config file
  become:
    yes
  template:
    src: config.j2
    dest: '{{remote_working_directory}}/ccc_assg2/harvester/config.json'

- name: Create couchdb config file
  become:
    yes
  template:
    src: connect_db.j2
    dest: '{{remote_working_directory}}/ccc_assg2/harvester/connect_db.py'

- name: docker build image
  shell: docker build --no-cache -t comp90024-harvester . 
  args:
    chdir: "/home/ubuntu/COMP90024/ccc_assg2/harvester/"