version: '3'
services:
    harvester:
        build: .
        volumes:
            - .:/usr/src/app
        deploy:
            replicas: 1
            update_config:
                parallelism: 2
                delay: 10s
            restart_policy:
                condition: on-failure