version: '3'
services:
    harvester:
        image: comp90024-harvester:latest
        ports:
            - 5000:80
        volumes:
            - .:/usr/src/app
        deploy:
            replicas: 2
            update_config:
                parallelism: 2
                delay: 10s
            restart_policy:
                condition: on-failure