# Configure group key in localhost
- hosts: localhost
  gather_facts: true

  roles:
    - role: config-groupkey

# Configure instances with common requireements.
- hosts: all
  vars_files:
    - host_vars/config.yaml
  gather_facts: true

  roles:
    - config-proxy
    - config-common
    - config-git-repository
    - config-docker
    - config-volumes
    
# Configure docker swarm
- hosts: masternode
  vars_files:
    - host_vars/config.yaml
  gather_facts: true
  remote_user: ubuntu
  become: yes
  become_method: sudo
  
  roles:
    - config-swarm

- hosts: workers
  vars_files:
    - host_vars/config.yaml
  gather_facts: true
  remote_user: ubuntu
  become: yes
  become_method: sudo
  
  roles:
    - config-worker-nodes