# Configure group key in localhost
- hosts: localhost
  gather_facts: true

  roles:
    - role: config-groupkey

# Configure instances with common requirements.
- hosts: all
  vars_files:
    - host_vars/config.yaml
  gather_facts: true
  remote_user: ubuntu
  become: yes
  become_method: sudo

  roles:
    - config-proxy
    - config-common
    - config-volumes
    - config-docker