---
- name: Deploy the harvester stack
  # https://docs.ansible.com/ansible/latest/modules/docker_stack_module.html
  docker_stack:
    state: present
    name: "{{ STACK_NAME | default('harvester') }}"
    compose:
      - "/home/ubuntu/COMP90024/ccc_assg2/harvester/docker-compose.yml"